# Generated by Django 5.1 on 2024-08-16 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='addressclient',
            new_name='account_add_address_88f0d2_idx',
            old_name='address_cli_address_4581de_idx',
        ),
        migrations.AlterModelTable(
            name='addressclient',
            table=None,
        ),
    ]
