# Generated by Django 5.1 on 2024-08-18 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date et heure de la création de l'enregistrement.", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text="Date et heure de la dernière mise à jour de l'enregistrement.", verbose_name='Date de mise à jour')),
                ('name', models.CharField(help_text='Le nom du produit.', max_length=255, unique=True, verbose_name='Nom du produit')),
                ('description', models.TextField(blank=True, help_text='Une brève description du produit.', null=True, verbose_name='Description')),
                ('quantity', models.PositiveIntegerField(help_text='La quantité disponible en stock.', verbose_name='Quantité en stock')),
                ('unit', models.CharField(help_text="L'unité de mesure pour ce produit (par ex: kg, litre, etc.).", max_length=50, verbose_name='Unité de mesure')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date et heure de la création de l'enregistrement.", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text="Date et heure de la dernière mise à jour de l'enregistrement.", verbose_name='Date de mise à jour')),
                ('name', models.CharField(help_text="Le nom de l'emplacement de stockage.", max_length=255, unique=True, verbose_name="Nom de l'emplacement")),
                ('address', models.TextField(blank=True, help_text="L'adresse de l'emplacement de stockage.", null=True, verbose_name='Adresse')),
            ],
            options={
                'verbose_name': 'Emplacement de stock',
                'verbose_name_plural': 'Emplacements de stock',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date et heure de la création de l'enregistrement.", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text="Date et heure de la dernière mise à jour de l'enregistrement.", verbose_name='Date de mise à jour')),
                ('quantity', models.PositiveIntegerField(help_text='La quantité du produit déplacé.', verbose_name='Quantité déplacée')),
                ('movement_date', models.DateTimeField(auto_now_add=True, help_text="La date et l'heure du mouvement de stock.", verbose_name='Date du mouvement')),
                ('from_location', models.ForeignKey(help_text="L'emplacement source d'où le produit est déplacé.", on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_movements', to='stock.stocklocation', verbose_name="De l'emplacement")),
                ('product', models.ForeignKey(help_text='Le produit déplacé.', on_delete=django.db.models.deletion.CASCADE, to='stock.product', verbose_name='Produit')),
                ('to_location', models.ForeignKey(help_text="L'emplacement destination où le produit est déplacé.", on_delete=django.db.models.deletion.CASCADE, related_name='incoming_movements', to='stock.stocklocation', verbose_name="À l'emplacement")),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-movement_date'],
            },
        ),
    ]
