# Generated by Django 5.1 on 2024-08-20 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.ForeignKey(default=1, help_text="L'emplacement de stockage initial pour ce produit.", on_delete=django.db.models.deletion.CASCADE, to='stock.stocklocation', verbose_name='Emplacement de stockage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogramme'), ('g', 'Gramme'), ('mg', 'Milligramme'), ('l', 'Litre'), ('ml', 'Millilitre'), ('cm', 'Centimètre'), ('m', 'Mètre'), ('piece', 'Pièce'), ('box', 'Boîte'), ('pack', 'Pack'), ('bottle', 'Bouteille'), ('dozen', 'Douzaine'), ('can', 'Canette'), ('jar', 'Pot'), ('bag', 'Sac')], help_text="L'unité de mesure pour ce produit.", max_length=50, verbose_name='Unité de mesure'),
        ),
    ]
