from .AddressRestaurantAdmin import AddressRestaurantAdmin
from .CategoryMenuItemAdmin import CategoryMenuItemAdmin
from .CategoryRestaurantAdmin import CategoryRestaurantAdmin
from .MenuAdmin import MenuAdmin
from .MenuItemAdmin import MenuItemAdmin
from .PhotoMenuItemAdmin import PhotoMenuItemAdmin
from .RestaurantAdmin import RestaurantAdmin
from .ReviewAdmin import ReviewAdmin
from .TypeMenuItemAdmin import TypeMenuItemAdmin
