# Generated by Django 5.1 on 2024-08-21 12:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text="Date et heure de la création de l'enregistrement.", verbose_name='Date de création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text="Date et heure de la dernière mise à jour de l'enregistrement.", verbose_name='Date de mise à jour'),
        ),
        migrations.AddField(
            model_name='loyaltypoint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text="Date et heure de la création de l'enregistrement.", verbose_name='Date de création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loyaltypoint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text="Date et heure de la dernière mise à jour de l'enregistrement.", verbose_name='Date de mise à jour'),
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text="Date et heure de la création de l'enregistrement.", verbose_name='Date de création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text="Date et heure de la dernière mise à jour de l'enregistrement.", verbose_name='Date de mise à jour'),
        ),
        migrations.AddField(
            model_name='useddiscount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text="Date et heure de la création de l'enregistrement.", verbose_name='Date de création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useddiscount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text="Date et heure de la dernière mise à jour de l'enregistrement.", verbose_name='Date de mise à jour'),
        ),
    ]
