# Generated by Django 5.1 on 2024-08-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('unavailable', 'Indisponible'), ('out_of_stock', 'En rupture de stock')], default='available', help_text="Indique la disponibilité de l'élément de menu.", max_length=15, verbose_name='Statut'),
        ),
    ]
