# Generated by Django 5.1 on 2024-08-16 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='addressrestaurant',
            new_name='restaurant__address_d1d1a5_idx',
            old_name='address_res_address_33fbe6_idx',
        ),
        migrations.RenameIndex(
            model_name='cartitem',
            new_name='restaurant__cart_id_a1aff3_idx',
            old_name='cart_item_cart_id_7d46c0_idx',
        ),
        migrations.RenameIndex(
            model_name='menu',
            new_name='restaurant__name_25f7fc_idx',
            old_name='menu_name_b58841_idx',
        ),
        migrations.RenameIndex(
            model_name='menuitem',
            new_name='restaurant__name_0490d9_idx',
            old_name='menu_item_name_33793c_idx',
        ),
        migrations.RenameIndex(
            model_name='orderitem',
            new_name='restaurant__order_i_21d94e_idx',
            old_name='order_item_order_i_f7aa2b_idx',
        ),
        migrations.RenameIndex(
            model_name='photomenuitem',
            new_name='restaurant__menu_it_4d13b2_idx',
            old_name='photo_menu__menu_it_461a83_idx',
        ),
        migrations.RenameIndex(
            model_name='restaurant',
            new_name='restaurant__name_cf5999_idx',
            old_name='restaurant_name_d51441_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='restaurant__menu_it_1deece_idx',
            old_name='review_menu_it_1f592b_idx',
        ),
        migrations.RenameIndex(
            model_name='typemenuitem',
            new_name='restaurant__name_30945a_idx',
            old_name='type_menu_i_name_b6e104_idx',
        ),
        migrations.AlterModelTable(
            name='addressrestaurant',
            table=None,
        ),
        migrations.AlterModelTable(
            name='cart',
            table=None,
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table=None,
        ),
        migrations.AlterModelTable(
            name='menu',
            table=None,
        ),
        migrations.AlterModelTable(
            name='menuitem',
            table=None,
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table=None,
        ),
        migrations.AlterModelTable(
            name='payment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='paymentmethod',
            table=None,
        ),
        migrations.AlterModelTable(
            name='photomenuitem',
            table=None,
        ),
        migrations.AlterModelTable(
            name='reservation',
            table=None,
        ),
        migrations.AlterModelTable(
            name='restaurant',
            table=None,
        ),
        migrations.AlterModelTable(
            name='review',
            table=None,
        ),
        migrations.AlterModelTable(
            name='typemenuitem',
            table=None,
        ),
    ]
