# Generated by Django 5.1 on 2024-08-20 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menuitem_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_total',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Le montant total pour cet article, basé sur la quantité.', max_digits=10, verbose_name="Montant total de l'article"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(editable=False, help_text='Le numéro unique de la commande.', max_length=100, unique=True, verbose_name='Numéro de commande'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('preparing', 'En préparation'), ('ready', 'Prête'), ('delivered', 'Livré'), ('canceled', 'Annulée')], default='pending', help_text='Le statut actuel de la commande.', max_length=50, verbose_name='Statut de la commande'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, help_text='Le montant total de la commande.', max_digits=10, verbose_name='Montant total'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(help_text='La commande à laquelle cet article appartient.', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='restaurant.order', verbose_name='Commande'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(help_text='La quantité de cet élément dans la commande.', verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='typemenuitem',
            name='name',
            field=models.CharField(help_text="Le nom du type d'élément de menu. Possibilités : Plat, Boisson, Dessert, Entrée, Accompagnement, etc.", max_length=255, verbose_name='Nom'),
        ),
    ]
