# Generated by Django 5.1 on 2024-08-16 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_rename_address_res_address_33fbe6_idx_restaurant__address_d1d1a5_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymenuitem',
            options={'ordering': ['name'], 'verbose_name': "Catégorie d'article de menu", 'verbose_name_plural': "Catégories d'articles de menu"},
        ),
    ]
