# Generated by Django 5.1 on 2024-08-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_orderitem_unique_together_orderitem_item_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.PositiveIntegerField(editable=False, help_text='Le numéro unique de la commande.', unique=True, verbose_name='Numéro de commande'),
        ),
    ]
