# Generated by Django 5.1 on 2024-08-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.IntegerField(editable=False, help_text='Le numéro unique de la commande.', unique=True, verbose_name='Numéro de commande'),
        ),
    ]
